controllers/LotController.php
<?php 

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\components\filters\AuthFilter;
use app\components\filters\LotAccessFilter;
use app\components\filters\CreateDealFilter;
use app\components\filters\TenderAccessFilter;
use app\components\filters\RiskIsActive;
use app\components\filters\SpecialistFilter;


use app\models\Lot;
use app\models\LotStatus;
use app\models\LotIndication;
use app\models\LotPercent;
use app\models\LotConclusion;
use app\models\User;
use app\models\LotSign;
use app\models\LotFile;
use app\models\DepList;
use app\models\Document;
use app\models\LotRisk;
use app\models\AppProvision;
use app\models\AgreementProvision;
use app\models\LotProtocol;
use app\models\ManagerHistory;
use app\models\ParticipateHistory;
use app\models\RiskFile;
use app\models\LotChat;



/**
 * 
 */
class LotController extends Controller
{

	public function behaviors()
	{
		return [
			[
				'class' => AuthFilter::className(),
			],
			[
				'class' => LotAccessFilter::className(),
				'only' => ['view']
 			],
			[
				'class' => TenderAccessFilter::className(),
				'only' => ['edit', 'create']
			],
			[
				'class' => CreateDealFilter::className(),
				'only' => ['create-deal', 'create-new-deal']
			],
			[
				'class' => SpecialistFilter::className(),
				'only' => ['create', 'store', 'update']
			],
		];
	}

	public function actionView($id)
	{	
		$userlist = Yii::$app->CacheComponent->getUsers();
		$deplist = Yii::$app->CacheComponent->getDepList();
		$protocols = Yii::$app->CacheComponent->getProtocols();

		$lot_info = Lot::infoByLotId($id);

		//return json_encode($lot_info);

		$lot_info['depids'] = explode(',', $lot_info['depids']);

		$managers = User::getByDepid();
		
		$documents = Document::all();
		$need_docs = Document::getById($id);

		$lot_risk = LotRisk::get($id);
		$signed_users = LotSign::all($id);
		$riskFiles = RiskFile::get($id);

		$risks = Yii::$app->RiskComponent->get($lot_risk, $signed_users, $riskFiles);

		$application_provision = AppProvision::getById($id);
		$agreement_provision = AgreementProvision::getById($id);
		
		$isNeedMakeSolution = ParticipateHistory::isNeedMakeSolution($id);
		$allSolutions = ParticipateHistory::getAllSolutions($id);
		$isNeedApproveSolution = ParticipateHistory::isNeedApproveSolution($id);
		
		$is_has_tv = Lot::isHasTv($id);
		$doc_files = Document::getDocFiles($id);
		$lot_participants = Lot::getParticipants($id);
		
		$lot_protocols = LotProtocol::getLotProtocols($id);
		$lot_protocol_files = LotProtocol::getFiles($id);
		$lot_deals = Lot::getDeals($id);
		$manager_history = ManagerHistory::get($id);

		$reasonsList = [ '0' => 'N/A', '1' => 'По квалификационной части', '2' => 'По технической части', '3' => 'По ценовой', '4' => 'Другое'];

		return $this->render('/lot/info', compact('managers', 'lot_deals', 'lot_info', 'userlist', 
			'is_has_tv', 'deplist', 'documents', 'need_docs', 'doc_files', 'lot_participants', 
			'application_provision', 'agreement_provision', 'protocols', 
			'lot_protocols', 'lot_protocol_files', 'manager_history', 'isNeedApproveSolution',
			'allSolutions', 'isNeedMakeSolution', 'risks', 'reasonsList'));
	}

	public function actionMessages($lotId)
	{	
		$lot_messages = LotChat::getLotMessages($lotId);

		return $this->asJson(['messages' => $lot_messages]);
	}

	public function actionEdit($id, $tenderid)
	{
		$lot_info = Lot::infoByLotId($id);
		$lot_statuses = Yii::$app->CacheComponent->getLotStatuses();
		$lot_indications = Yii::$app->CacheComponent->getLotIndications();
		$percents = Yii::$app->CacheComponent->getLotPercents();
		$conclusions = Yii::$app->CacheComponent->getLotConclusions();

		return $this->render('/lot/edit', compact('lot_info', 'lot_statuses', 'lot_indications', 'percents', 'conclusions'));
	}

	function get_type($elem)
	{
		return $elem['userid'];
	}

	public function actionNotify()
	{
		$lots = Lot::getLotsForNotifications();
		$final = [];
		$managers = [];

		//return json_encode($lots);

		foreach($lots as $index => $lot) {
			if(($lot['ap_is_need'] == 1 && $lot['ap_is_exist'] == 0) || ($lot['lap_is_need'] == 1 && $lot['lap_is_exist'] == 0)) {
				$final[] = $lot;
				//$managers[] = $lot['m_managerid'];
			}
		}

		if(count($final)) {

			$departments = []; 

			foreach($final as $k => $lot) {
				$query = (new \yii\db\Query())
				->select('u.userid, u.login, u.fullname, u.position, u.depid, u.email')
				->from('contracts.users u')
				->where(['blocked'=> 0])
				->andWhere(['!=', 'userid', 0])
				->andWhere(['=', 'userid', $lot['m_managerid']])
				->orderBy(['u.fullname' => SORT_ASC])
				->one();
	
				$final[$k]['depId'] = $query['depid'];
				$departments[] = (int) trim($query['depid']);
				$managers[] = [
					'userid' => $lot['m_managerid'],
					'depid' => $query['depid']
				];
			}
	
			$managers = array_unique($managers, SORT_REGULAR);
			$departments = array_unique($departments);
	
			// Form user list
	
			$users = (new \yii\db\Query())
			->select(['privusers.userid', 'privusers.depid'])
			->from('privusers')
			->where(['privusers.depid' => $departments])
			->andWhere(['privusers.tender' => [3] ])
			->all();

			// Арман Маралов 240
			// Эркин Орозакунов 1460

			$users = array_merge($users, $managers);

			//->andWhere(['=', 'privusers.tender', 1])
			//->all();
	
			/* if(count($departments)) {
	
				$users = $users->where(['privusers.depid' => $departments])->all();
				$users = array_merge($users, $managers);
	
			} else {
	
				$users = $users->all();
				$users = array_merge($users, $managers);
			} */
	
			//return json_encode($users);
			//return json_encode($final);

			foreach($final as $key => $lot) {
				foreach($users as $j => $user) {
					if($user['depid'] == $lot['depId']) {
						//return json_encode(['userid' => $user['userid'], 'lotid' => $lot['lotid']]);
						Yii::$app->MailComponent->sendToUser($user['userid'], $lot['lotid']);
					}
				}
			}

			Yii::$app->MailComponent->sendToUser(1810, $lot['lotid']);
	
			//return json_encode(['lots' => $final, 'users' => $users]);
			return json_encode(['success' => true]);
		}
	}

	public function actionUpdate($id, $tenderid)
	{
		$lot = new Lot();

		//return $lot->edit($id);

		if ($lot->edit($id)) {
			Yii::$app->session->setFlash('success', "Лот изменен успешно.");
		} else {
			Yii::$app->session->setFlash('error', "Лот не изменен.");
		}

		return $this->redirect(['lot/view', 'id'=>$id]);
	}

	public function actionCreate($tenderid)
	{
		$lot_statuses = Yii::$app->CacheComponent->getLotStatuses();
		$lot_indications = Yii::$app->CacheComponent->getLotIndications();
		$percents = Yii::$app->CacheComponent->getLotPercents();
		$conclusions = Yii::$app->CacheComponent->getLotConclusions();

		return $this->render('/lot/create', compact('lot_info', 'lot_statuses', 'lot_indications', 'percents', 'conclusions'));
	}

	public function actionStore($tenderid)
	{
		$lot = new Lot();
		$lot_file = new LotFile();
		
		if ($lot->store()) {

			$lot_file->uploadFile($lot->lotid);
			Yii::$app->session->setFlash('success', "Лот успешно создан.");
		} else {
			Yii::$app->session->setFlash('error', "Не удалось создать лот");
		}

		return $this->redirect(['lot/view', 'id'=> $lot->lotid]);
			
	}

	public function actionCreateDeal($id, $dealid)
	{
		$lot = new Lot();

		if ($lot->assignLotToDeal($id, $dealid)) {

				$this->getLinkToDeal($lot->csid, $id);
					
				Yii::$app->session->setFlash('success', "Лот был привязан к сделки из kCRM");
		} else {
			Yii::$app->session->setFlash('error', "Упс :(. Ошибка!");
		}

		return $this->redirect(['lot/view', 'id'=>$id]);
	}

	
	public function actionCreateNewDeal($id)
	{
		error_reporting(E_ALL & ~E_DEPRECATED & ~E_NOTICE);
		$lot = new Lot();

		if ($lot->createDeal($id)) {

			$this->getLinkToDeal($lot->csid, $id);
		
				Yii::$app->session->setFlash('success', "Сделка была успешно создана в kCRM");
		} else {
				Yii::$app->session->setFlash('error', "Сделка не была создана в KCRM");
		}
		
		return $this->redirect(['lot/view', 'id'=>$id]);
	}

	public function getLinkToDeal($csid, $lotid)
	{
		$soap='xreq=
            <soapenv:Envelope">
            <soapenv:Header>
            <heads:credentials">
            <heads:key>69av92us40jn</heads:key>
            </heads:credentials>
            </soapenv:Header>
            <soapenv:Body>
            <get_ecsid_by_csid>'.$csid.'</get_ecsid_by_csid>
            </soapenv:Body>
            </soapenv:Envelope>';

       	$headers = array(
            'POST /apihub/index.php',
            'Host: kcrm.kaztranscom.kz',
            'Content-Length: '.strlen($soap));

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, 'https://kcrm.kaztranscom.kz/apihub/index.php');
        curl_setopt($ch, CURLOPT_HEADER, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_USERAGENT, "Opera/9.63 (Windows NT 5.1; U; ru) Presto/2.1.1");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers); 
        curl_setopt($ch, CURLOPT_POST, true );
        curl_setopt($ch, CURLOPT_POSTFIELDS, $soap);
        $result = curl_exec($ch);
        curl_close($ch);
      
        $ecsid = $result;
       
      	if (Lot::linkToDeal($ecsid, $lotid)) {
      		Yii::$app->session->setFlash('success', "Вы успешно создали сделку в KCRM. Ссылку была сгенерирована и будет доступна в информации о лоте.");
      		return true;
		}

		return false;     	
	}

	public function actionSign($risk_id, $lotid)
	{
		if (LotSign::sign($risk_id, $lotid)) {
			Yii::$app->session->setFlash('success', "Вы успешно подписали лот, поздравляем.");
		} else {
			Yii::$app->session->setFlash('error', "К сожалению, не удалось подписать лот. Попробуйте снова.");
		}

		return $this->redirect(['lot/view', 'id'=>$lotid]);
	}

	public function actionDownloadFile($id)
	{
		return LotFile::download($id);
	}

views/lot/partials/_make_solution.php
<div class="form-group" id="participate-block">
	<div class="row">
		<div class="col-md-6">
			<textarea class="form-control" cols="2" type="text" id="participate-reason-textarea" placeholder="Причина, которая стала основанием для не участия в тендере" ></textarea>
		</div>
		<div class="col-md-12" style="margin-top: 20px;">
			<button type="submit" id="btn-submit" name="is_sign" class="btn btn-success btn-xs" onclick="isParticipate(1, <?=$id?>, <?=$idButton?>)">Участвуем</button>
			<button type="submit" id="btn-submit" name="is_sign" class="btn btn-danger btn-xs" onclick="isParticipate(0, <?=$id?>, <?=$idButton?>)">Не участвуем</button>
		</div>
	</div>
</div>

views/lot/partials/_risk.php
<?php 
use kartik\select2\Select2; 
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
?>

<?php foreach ($risks as $i => $risk): ?>

<div id="<?='risk_'.$risk['lr_id']?>" class="one_risk">
<div class="panel-body">
	<div class="row">
		<div class="col-md-12">
				<?php if ($risk['lr_title'] == NULL): ?>
					<h4 id="<?='risk_title_'.$risk['lr_id']?>" style="color:red;">Риски не описаны.</h4>
				<?php else: ?>
				<h4 id="<?='risk_title_'.$risk['lr_id']?>"><?= nl2br($risk['lr_title']) ?></h4>
				<?php endif ?>

				<textarea class="form-control" id="<?='risk_textarea_'.$risk['lr_id']?>" cols="30" rows="5" style="display: none;"><?= $risk['lr_title'] ?></textarea>
		</div>
			<div class="col-md-6 col-md-offset-6" style="margin-top: 15px;">
				<div class="col-md-6">
					<div id="<?='risk_info_'.$risk['lr_id']?>" style="display: block;">
						<b>Последние изменения от:</b><br>
						<i id="<?='author_of_risk_'.$risk['lr_id']?>"><?= $risk['lr_fullname']?></i><br>
						<i id="<?='date_of_risk_'.$risk['lr_id']?>"><?= date('d-m-Y H:i', $risk['lr_updated_at']) ?></i>
					</div>
				</div>
				<div class="col-md-6">
					<?php if ($user_tender_permission == 1 || $user_tender_permission == 2): ?>
						<button class="btn btn-default btn-xs" id="<?='risk_create_button_'.$risk['lr_id']?>" style="float: right;" onclick="createRisk(<?=$risk['lr_id']?>, <?= $lot_info['l_tenderid'] ?>)">Описать риски</button>
						<button class="btn btn-success btn-xs" id="<?='risk_save_button_'.$risk['lr_id']?>" style="float: right; display: none" onclick="saveRisk(<?=$risk['lr_id']?>, <?= $lotid ?>, <?= $lot_info['l_tenderid'] ?>)">Сохранить</button>
					<?php endif ?>
				</div>
			</div>
			<div class="col-md-12">
				<div class="form-group">
					<b>Вложения:</b><br><br>
					<div id="<?='risk_files_'.$risk['lr_id']?>">
					<?php if (isset($risk['files'])): ?>
							<?php foreach ($risk['files'] as $k => $file): ?>
								<span id="<?='risk_file_'.$file['rf_id']?>">
									<a target="_blank" href="<?=Url::toRoute(['risk-ajax/download-file', 'id' => $file['rf_id']])?>"><?=$file['rf_filename']?></a><button type="button"  class="btn btn-outline-danger btn-xs" title="Удалить файл" onclick="rmRiskFile(<?=$file['rf_id']?>, <?=$risk['lr_id']?>)"><i class="fa fa-remove" aria-hidden="true" style="color:red;"></i></button><br>
								</span>
							<?php endforeach ?>
					<?php endif ?>
					</div>
					<?php if ($user_tender_permission == 1 || $user_tender_permission == 2): ?>
						<input name="risk-file" type="file" id="<?='risk-file-input-'.$risk['lr_id']?>" class="inp01" accept=".xlsx,.xls,image/*,.doc, .docx,.ppt, .pptx,.txt,.pdf" onchange="uploadRiskFile(<?=$risk['lr_id']?>, <?=$lotid?>, <?= $lot_info['l_tenderid'] ?>);">
					<?php endif ?>		
				</div>


			</div>
		</div>
</div>



<div class="table-responsive">
    <table class="table table-striped table-condensed" id="<?='table_signed_'.$risk['lr_id']?>">
        <thead>
            <tr>
                <th>ФИО</th>
                <th>Подразделение</th>
                <th>Дата получения</th>
                <th>Подписал</th>
                <th>Дата подписания</th>
                <th>Комментарий</th>                                          
            </tr>
        </thead>   
        <tbody>
        <?php if (isset($risk['signers'])): ?>
        	<?php foreach ($risk['signers'] as $j => $signer): ?>
            <tr id="<?= 'signed_user_'.$signer['sid'] ?>">
                <td><?= $signer['s_username'] ?></td>
                <td><?= $signer['s_dname'] ?></td>
                <td><?= date('d-m-Y', $signer['s_date_received']) ?></td>
                <td><?= $signer['is_signed'] ? '<span class="glyphicon glyphicon-ok" style="color:green">' : '<span class="glyphicon glyphicon-remove" style="color:red">' ?></td>
                <td><?= $signer['s_date_signed'] ? date('d-m-Y', $signer['s_date_signed']) : 'Еще не подписал' ?> </td>
                <td><?= $signer['s_comment'] ?></td>
                <?php if ($user_tender_permission == 1 || $user_tender_permission == 2): ?>
                    <td><button type="button" id="remove" class="btn btn-danger btn-xs" onclick="rmUser(<?=$signer['sid']?>, <?=$risk['lr_id']?>)" style="margin-left: 20px;">Удалить</button></td>
                <?php endif ?>                                   
            </tr>  
        	<?php endforeach ?>	
        <?php endif ?>                               
        </tbody>
    </table>
</div>
<?php if (isset($risk['is_need_sign']) && $risk['lr_isActive'] == 1): ?>
	<div class="col-md-6">
        <form class="form" role="form" method="POST" action="<?=Url::toRoute(['lot/sign', 'risk_id'=>$risk['lr_id'], 'lotid'=>$lotid])?>">
        <input type="hidden" name="<?= Yii::$app->request->csrfParam; ?>" value="<?= Yii::$app->request->csrfToken; ?>" />
            <div class="form-group">
                <textarea class="form-control" cols="4" type="text" name="comment" placeholder="Комментарий" ></textarea>
            </div>
            <div class="form-group">
            
            </div>
            <div class="form-group">
                <button type="submit" id="btn-submit" name="is_sign" class="btn btn-success btn-xs" value="1">Принять</button>
                <button type="submit" id="btn-submit" name="is_sign" class="btn btn-danger btn-xs" value="0">Отклонить</button>
            </div>
        </form>
    </div>	
<?php endif ?>
<?php if ($user_tender_permission == 1 || $user_tender_permission == 2): ?>
    <div class="col-md-12" >
        <div class="col-md-6">
            <div class="controls"><br>
                <b>Выберите подписантов, которые должны согласовать данный лот.</b><br><br>
                <?= Select2::widget([
                    'name' => 'is_affiliated',
                    'value' => 0,
                    'data' => ArrayHelper::merge(['0' => 'Не выбрано'], ArrayHelper::map($userlist, 'userid', 'fullname')),
                    'options' => ['multiple'=>false, 'class' => 'inp01'],
                    'pluginOptions' => [
                        'width' => '200px',
                    ],
                    'pluginEvents' => [
                        'select2:select' => 'function() { addUser(this.value, '.$risk['lr_id'].', '.$lotid.') }'
                    ],
                ]);
                ?>
            </div>
        </div>
        <div class="col-md-4">
            <div class="controls"><br>
                <b>Запустив на согласование, изменить риски и вложения нельзя!</b>
                <br><br>

                <?php if ($risk['lr_isActive'] == 0): ?>
                    <button id="<?='risk-is-active-0-'.$risk['lr_id']?>" class="btn btn-danger" onclick="riskIsActive(0, <?=$risk['lr_id']?>, <?= $lotid ?>, <?= $lot_info['l_tenderid'] ?>)" style="display:none;">Отозвать согласование</button>
                    <button id="<?='risk-is-active-1-'.$risk['lr_id']?>" class="btn btn-default" onclick="riskIsActive(1,<?=$risk['lr_id']?>, <?= $lotid ?>, <?= $lot_info['l_tenderid'] ?>)">Запустить на согласование</button>
                <?php else: ?>
                    <button id="<?='risk-is-active-1-'.$risk['lr_id']?>" class="btn btn-default" onclick="riskIsActive(1, <?=$risk['lr_id']?>, <?= $lotid ?>, <?= $lot_info['l_tenderid'] ?>)" style="display:none;">Запустить на согласование</button>
                    <button id="<?='risk-is-active-0-'.$risk['lr_id']?>" class="btn btn-danger" onclick="riskIsActive(0, <?=$risk['lr_id']?>, <?= $lotid ?>, <?= $lot_info['l_tenderid'] ?>)">Отозвать согласование</button>
                <?php endif ?>
            </div>
        </div>
    </div>
<?php endif ?>
</div>
<div style="height: 150px; border-bottom: 1px solid black"></div>
<?php endforeach ?>