controllers/TenderController.php
<?php 

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\components\filters\AuthFilter;
use app\components\filters\SpecialistFilter;
use app\components\filters\TenderAccessFilter;
use yii\data\ArrayDataProvider;

use app\models\Auth;
use app\models\Tender;
use app\models\Lot;
use app\models\Csinfo;
use app\models\TenderSource;
use app\models\TenderSector;
use app\models\TenderFile;
use app\models\DepList;
use app\models\User;
use app\models\TenderOrig;
use app\models\TenderProtocol;
use app\models\ProtocolFile;



/**
 * 
 */
class TenderController extends Controller
{

	public function behaviors()
	{
		return [
			// [
			//  'class' => AuthFilter::className(),
			// ],
            [
             'class' => TenderAccessFilter::className(),
             'only' => ['create', 'edit', 'update']
            ],
            [
                'class' => SpecialistFilter::className(),
                'only' => ['edit', 'update']
            ]
		];
	}

	public function actionIndex()
    {   
        $userlist = Yii::$app->CacheComponent->getDrtpSpecialists();

        $isParticipate = [
            ['value' => 0, 'title' => 'Не Выбрано'], 
            ['value' => 1, 'title' => 'Отказ'], 
            ['value' => 2, 'title' => 'Участвуем']
        ];

    	$provider = new ArrayDataProvider([
			'allModels' => Tender::getAll(),
			'sort' => [
				'attributes' => [
					'tenderid',
					'senddate',
					'source_title',
					't_ccsid',
					't_csbin',
					't_csname',
                    'accept_solution',
					'purchase_title',
                    'tender_userid',
                    'tender_username',
					'purchase_number',
					'purchase_name',
                    'actid',
                    'aid_signed_agreements',
                    'updated_at',
                    'lot_counts_tv', 
                    'lot_participate_count_true',
				],
                'defaultOrder' => [ 
                    //'lot_participate_count_true' => SORT_DESC,
                    //'lot_counts_tv'=>SORT_DESC,
                    'updated_at'=> SORT_DESC, 
                ]
			],
			'pagination' => [
				'pageSize' => 25,
			],
		]);

		$tenders = $provider->getModels();

		return $this->render('/tender/index', compact('provider', 'tenders', 'userlist', 'isParticipate'));

    }

    public function actionFiled()
    {
        $userlist = Yii::$app->CacheComponent->getDrtpSpecialists();

        $provider = new ArrayDataProvider([
            'allModels' => Tender::getFiled(),
            'sort' => [
                'attributes' => [
                    'tenderid',
                    'senddate',
                    'source_title',
                    't_ccsid',
                    't_csbin',
                    't_csname',
                    'accept_solution',
                    'purchase_title',
                    'tender_userid',
                    'tender_username',
                    'purchase_number',
                    'purchase_name',
                    'actid',
                    'aid_signed_agreements',
                    'updated_at',
                    'lot_counts_tv', 
                    'lot_participate_count',
                ],
                'defaultOrder' => [ 
                    'lot_participate_count' => SORT_DESC,
                    'lot_counts_tv'=>SORT_DESC,
                    'updated_at'=>SORT_DESC, 
                ]
            ],
            'pagination' => [
                'pageSize' => 25,
            ],
        ]);

        $tenders = $provider->getModels();

        return $this->render('/tender/filed', compact('provider', 'tenders', 'userlist'));
    }

    public function actionWorked()
    {
        $userlist = Yii::$app->CacheComponent->getDrtpSpecialists();

        $provider = new ArrayDataProvider([
            'allModels' => Tender::getWorked(),
            'sort' => [
                'attributes' => [
                    'tenderid',
                    'senddate',
                    'source_title',
                    't_ccsid',
                    't_csbin',
                    't_csname',
                    'accept_solution',
                    'purchase_title',
                    'tender_userid',
                    'tender_username',
                    'purchase_number',
                    'purchase_name',
                    'actid',
                    'aid_signed_agreements',
                    'updated_at',
                    'lot_counts_tv', 
                    'lot_participate_count',
                ],
                'defaultOrder' => [ 
                    'lot_participate_count' => SORT_DESC,
                    'lot_counts_tv'=>SORT_DESC,
                    'updated_at'=>SORT_DESC, 
                ]
            ],
            'pagination' => [
                'pageSize' => 25,
            ],
        ]);

        $tenders = $provider->getModels();

        return $this->render('/tender/worked', compact('provider', 'tenders', 'userlist'));
    }

    public function actionUnWorked()
    {
        $userlist = Yii::$app->CacheComponent->getDrtpSpecialists();

        $provider = new ArrayDataProvider([
            'allModels' => Tender::getUnWorked(),
            'sort' => [
                'attributes' => [
                    'tenderid',
                    'senddate',
                    'source_title',
                    't_ccsid',
                    't_csbin',
                    't_csname',
                    'accept_solution',
                    'purchase_title',
                    'tender_userid',
                    'tender_username',
                    'purchase_number',
                    'purchase_name',
                    'actid',
                    'aid_signed_agreements',
                    'updated_at',
                    'lot_counts_tv', 
                    'lot_participate_count',
                ],
                'defaultOrder' => [ 
                    'lot_participate_count' => SORT_DESC,
                    'lot_counts_tv'=>SORT_DESC,
                    'updated_at'=>SORT_DESC, 
                ]
            ],
            'pagination' => [
                'pageSize' => 25,
            ],
        ]);

        $tenders = $provider->getModels();

        return $this->render('/tender/unworked', compact('provider', 'tenders', 'userlist'));
    }

    public function actionCreate()
    {
        $purchases = Yii::$app->CacheComponent->getPurchases();
        $sources = Yii::$app->CacheComponent->getSources();
        $sectors = Yii::$app->CacheComponent->getSectors();
        $origlist = Yii::$app->CacheComponent->getOrigList();
        $ognlist = Yii::$app->CacheComponent->getOgnList();

    	return $this->render('/tender/new', compact('purchases', 'sources', 'sectors', 'origlist', 'ognlist'));
    }

    public function actionEdit($tenderid)
    {
        $purchases = Yii::$app->CacheComponent->getPurchases();
        $sources = Yii::$app->CacheComponent->getSources();
        $sectors = Yii::$app->CacheComponent->getSectors();
        $origlist = Yii::$app->CacheComponent->getOrigList();
        $ognlist = Yii::$app->CacheComponent->getOgnList();


        $tender = Tender::info($tenderid);
    	return $this->render('/tender/edit', compact('purchases', 'sources', 'sectors', 'tender', 'origlist', 'ognlist'));
    }

    public function actionUpdate($id)
    {
    	$tender_obj = new Tender();
    	if ($tender_obj->edit($id)) {

    		Yii::$app->session->setFlash('success', 'Тендер успешно изменен.');
    		return $this->redirect(['tender/view', 'id'=>$id]);

    	} else {

            $purchases = Yii::$app->CacheComponent->getPurchases();
            $sources = Yii::$app->CacheComponent->getSources();
            $sectors = Yii::$app->CacheComponent->getSectors();
            $origlist = Yii::$app->CacheComponent->getOrigList();
            $ognlist = Yii::$app->CacheComponent->getOgnList();

            $tender = $tender_obj->info($id);

    		Yii::$app->session->setFlash('error', $tender_obj->error);
    		return $this->render('/tender/edit', compact('purchases', 'sources', 'sectors', 'tender', 'origlist', 'ognlist'));
    	}
    }

    public function actionTest()
    {
        //$lots = Yii::$app->UserComponent->getTenderLotManagers(1745);

        $result = Yii::$app->MailComponent->notifyLotManagers(1745);

        return json_encode($result);
    }

    public function actionView($id)
    {
    	$deplist = Yii::$app->CacheComponent->getDepList();
        $origlist = Yii::$app->CacheComponent->getOrigList();
        $ognlist = Yii::$app->CacheComponent->getOgnList();
        $protocols = Yii::$app->CacheComponent->getProtocols();

        $managers = Yii::$app->CacheComponent->getOnlyManagers();
        $tender = Tender::info($id);

        $tender_protocols = TenderProtocol::getAll($id);
        $tender_protocol_files = ProtocolFile::getAll($id);
    	$provider = new ArrayDataProvider([
			'allModels' => Lot::infoByTenderId($id),
			'pagination' => [
				'pageSize' => 25,
			],
        ]);
        
        $procurementList = [ '0' => 'N/A', '1' => 'ТО', '2' => 'ТК', '3' => 'СИ'];

		$lots = $provider->getModels();
    	return $this->render('/tender/info', compact('protocols', 'tender_protocols', 'tender_protocol_files', 'tender', 'lots', 'provider', 'deplist', 'userlist', 'managers', 'origlist', 'ognlist', 'procurementList'));
    }

    public function actionStore()
    {
    	$tender = new Tender();
        $tender_file = new TenderFile();

    	if ($tender->store()) {

            $tender_file->uploadFile($tender->id);

            Yii::$app->session->setFlash('success', 'Тендер успешно создан');
    		return $this->redirect(['tender/view', 'id'=>$tender->id]);

    	} else {

    		$purchases = Yii::$app->CacheComponent->getPurchases();
            $sources = Yii::$app->CacheComponent->getSources();
            $sectors = Yii::$app->CacheComponent->getSectors();

views/tender/new.php
<?php
use yii\helpers\Url;
use kartik\date\DatePicker;
// use kartik\datetime\DateTimePicker;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\web\JsExpression;

?>
<!-- 
<div class="row">
	<div class="col-md-6">
		<nav class="navbar navbar-default">
			<div class="container-fluid">
				<ul class="nav navbar-nav">
					<li class="active"><a href="#">Общая информация</a></li>
				</ul>
			</div>
		</nav>
	</div>
</div> -->

<div class="row" style="margin-top: 20px;">
	<div class="col-md-6">
		<form action="<?= Url::toRoute(['tender/store'])?>" method="POST" onkeypress="return event.keyCode!=13">
			<input type="hidden" name="<?= Yii::$app->request->csrfParam; ?>" value="<?= Yii::$app->request->csrfToken; ?>" />
			<input id="tmp_code" name="tmp_code" type="hidden" value="<?= Yii::$app->params['tmp_code']?>">
			<table class="table" style="width:100%;background:#ffffff;border:10px solid #ffffff;">
				<tbody>
					<tr>
						<td colspan="2" class="haction1">Информация о Тендере<br><br>
						</td>
					</tr>
					<tr>
						<td class="td01">Дата направления объявления на рассмотрение</td>
						<td class="td02">
							<?=  DatePicker::widget([
								'name' => 'senddate',
								'type' => DatePicker::TYPE_INPUT,
								'value' => date('d-m-Y'),
								'pluginOptions' => [
									'autoclose'=>true,
									'format' => 'dd-mm-yyyy',
								],
								'options' => ['class' => 'inp01']
							]);
							?>
						</td>
					</tr>
					<tr>
						<td class="td01">Дата окончания обсуждения</td><td class="td02">
							<?=  DatePicker::widget([
								'name' => 'date_end_discuss',
								'type' => DatePicker::TYPE_INPUT,
								'value' => date('d-m-Y'),
								'pluginOptions' => [
									'autoclose'=>true,
									'format' => 'dd-mm-yyyy',
								],
								'options' => ['class' => 'inp01']
							]);
							?>
						</td>
					</tr>
					<tr>
              <td class="td01">Установленная дата принятия решения об участии в закупке</td><td class="td02">
                  <?=  DatePicker::widget([
                      'name' => 'accept_solution',
                      'type' => DatePicker::TYPE_INPUT,
                      'value' => date('d-m-Y'),
                      'pluginOptions' => [
                          'autoclose'=>true,
                          'format' => 'dd-mm-yyyy',
                      ],
                      'options' => ['class' => 'inp01']
                  ]);
                  ?>
              </td>
          </tr>
           <tr>
              <td class="td01">Дата вскрытия</td><td class="td02">
                  <?=  DatePicker::widget([
                      'name' => 'date_purchase',
                      'type' => DatePicker::TYPE_INPUT,
                      'value' => date('d-m-Y'),
                      'pluginOptions' => [
                          'autoclose'=>true,
                          'format' => 'dd-mm-yyyy',
                      ],
                      'options' => ['class' => 'inp01']
                  ]);
                  ?>
              </td>
          </tr>
					<tr>
						<td width="50%" class="td01">Источник получения объявления</td><td width="50%" class="td02">
							<?= 
								Select2::widget([
									'name' => 'source_get',
								    'value' => 0,
								    'data' => ArrayHelper::map($sources, 'sourceid', 'source_title'),
								    'maintainOrder' => true,
								    'options' => ['class' => 'inp01', 'multiple' => false],
								    'pluginOptions' => [
								    	'tags' => true,
								    ],
								]);
							?>
						</td>
					</tr>
					<tr>
						<td class="td01">БИН Организатора / Заказчика закупок <span style="color:red">*</span></td><td class="td02">
						<?= 
							Select2::widget([
								'name' => 't_csbin',
							    'value' => '',
							    'options' => ['placeholder' => 'Введите БИН', 'onchange'=>'setCsIdAndName(this);', 'id'=>'t_csbin', 'type' => 'number'],
							    'pluginOptions' => [
							    	'tags' => true,
							    	'allowClear' => true,
							    	'minimumInputLength' => 5,
							    	'maximumInputLength' => 12,
							    	'language' => [
							    		'errorLoading' => new JsExpression("function () { return 'Waiting for results...'; }"),
							    		'inputTooShort' => new JsExpression("function () { return 'Введите минимум 5 символов'; }"),
							    	],
							    	'ajax' => [
							    		'url' => Url::to(['tender-ajax/search-bin']),
							    		'dataType' => 'json',
							    		'data' => new JsExpression('function(params) { return {q:params.term}; }')
							    	],
							    	'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
							    	'templateResult' => new JsExpression('function(cs) { return [cs.cdid, cs.text]; }'),
							    	'templateSelection' => new JsExpression('function (cs) { return cs.text; }'),
							    ],
							]);
						?>
						</td>
					</tr>
					<input id="t_csid" type = "hidden" name = "t_csid" value = "0" />
					<input id="t_csbin_text" type = "hidden" name = "t_csbin_text" value = "" />
					<input id="t_csname_text" type = "hidden" name = "t_csname_text" value = "" />
					<tr>
						<td class="td01">Тип предприятия</td>
						<td class="td02"><?= Select2::widget([
									'name' => 'origid',
								    'value' => 1,
								    'data' => ArrayHelper::map($origlist, 'origid', 'origname'),
								    'maintainOrder' => true,
								    'options' => ['class' => 'inp01', 'multiple' => false],
								    'pluginOptions' => [
								    	'tags' => true,
								    ],
								]); ?></td>
					</tr>
					<tr>
						<td class="td01">Форма собственности предприятия</td>
						<td class="td02"><?= Select2::widget([
									'name' => 'ognid',
								    'value' => 0,
								    'data' => ArrayHelper::map($ognlist, 'ognid', 'ognname'),
								    'maintainOrder' => true,
								    'options' => ['class' => 'inp01', 'multiple' => false],
								    'pluginOptions' => [
								    	'tags' => true,
								    ],
								]); ?></td>
					</tr>
					<tr>
						<td class="td01">Наименование Организатора/Заказчика закупок <span style="color:red">*</span></td><td class="td02"><?=

							Select2::widget([
								'name' => 't_csname',
							    'value' => '',
							    'options' => ['class' => 'inp01', 'multiple' => false, 'id'=>'t_csname',
							    'placeholder'=>'Введите название', 'onchange' => 'setCsName(this)'],
							    'pluginOptions' => [
							    	'tags' => true,
							    	'allowClear' => true,
							    	// 'minimumInputLength' => 5,
							    	'language' => [
							    		'errorLoading' => new JsExpression("function () { return 'Waiting for results...'; }"),
							    		'inputTooShort' => new JsExpression("function () { return 'Введите минимум 5 символов'; }"),
							    	],
							    	'ajax' => [
							    		'url' => Url::to(['tender-ajax/search-cs']),
							    		'dataType' => 'json',
							    		'data' => new JsExpression('function(params) { return {q:params.term}; }')
							    	],
							    	'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
							    	'templateResult' => new JsExpression('function(cs) { return [cs.cdid, cs.text]; }'),
							    	'templateSelection' => new JsExpression('function (cs) { return cs.text; }'),
							    ],
							]);
							?>		
						</td>
					</tr>
					<tr>
						<td class="td01">Сектор Организатора / Заказчика закупок</td><td class="td02">
							<?= 
							Select2::widget([
								'name' => 'sector',
							    'value' => '',
							    'data' => ArrayHelper::map($sectors, 'sectorid', 'sector_title'),
							    'maintainOrder' => true,
							    'hideSearch' => true,
							    'options' => ['class' => 'inp01', 'multiple' => false, ],
							    'pluginOptions' => [
							    	'tags' => true,

							    ],
							]);
							?>
						</td>
					</tr>
					<tr>
						<td class="td01">Вид закупки</td><td class="td02">
							<?= 
							Select2::widget([
								'name' => 't_purchase',
							    'value' => '',
							    'data' => ArrayHelper::map($purchases, 'purchaseid', 'purchase_title'),
							    'maintainOrder' => true,
							    'hideSearch' => true,
							    'options' => ['class' => 'inp01', 'multiple' => false, 'id'=>'t_purchase'],
							    'pluginOptions' => [
							    	'tags' => true,
							    	'maximumInputLength' => 20
							    ],
							]);
							?>
						</td>
					</tr>
					<tr>
						<td class="td01">Измененный вид закупки</td><td class="td02">
							<?= 
							Select2::widget([
								'name' => 'purchase_type_changed',
							    'value' => '',
							    'data' => ArrayHelper::map($purchases, 'purchaseid', 'purchase_title'),
							    'maintainOrder' => true,
							    'hideSearch' => true,
							    'options' => ['class' => 'inp01', 'multiple' => false, 'id'=>'t_purchase'],
							    'pluginOptions' => [
							    	'tags' => true,
							    	'maximumInputLength' => 20
							    ],
							]);
							?>
						</td>
					</tr>
					<tr>
                        <td class="td01">Консорциум</td><td class="td02">
                            <textarea name="consortium" type="text" id="consortium" class="inp01" autocomplete="off" cols="30" rows="3"></textarea>
                        </td>
                    </tr>
					<tr>
						<td class="td01">№ (номер) закупки</td><td class="td02">
							<input name="purchase_number" type="text" value="" id="purchase_number" class="inp01" autocomplete="off">
						</td>
					</tr>
					<tr>
						<td class="td01">Наименование закупок</td>
						<td class="td02">
							<input name="purchase_name" type="text" value="" id="purchase_name" class="inp01" autocomplete="off">
						</td>
					</tr>
					<tr>
						<td class="td01">Файлы</td>
						<td class="td02" id="tender_files">
							<input name="tender_file" type="file" value="" id="tender_file" class="inp01" accept=
							".xlsx,.xls,image/*,.doc, .docx,.ppt, .pptx,.txt,.pdf" onchange="uploadFile();">
						</td>
					</tr>
				</tbody>
			</table>
			<button class="btn btn-default" type="submit">Сохранить</button>
		</form>
	</div>
</div>

<script>
	function uploadFile()
	{
		var formData = new FormData();

		formData.append('file', $('#tender_file')[0].files[0]);
    formData.append('tmp_code',$('#tmp_code').val())

        $.ajax({
            url: 'index.php?r=tender-ajax%2Fupload-file',
            type: 'POST',
            mimeType: 'multipart/form-data',
            data: formData,   
            datatype:'json',
            cache: false,
            contentType: false,
            processData: false,

            success: function (data) {
                var result = JSON.parse(data);
                console.log(result);
                $('#tender_file').val("");

                var row = $("<div class='file_"+result.fileid+"' />")
                $('#tender_files').append(row);
                row.append($('<div class="drive-item module"><div class="drive-item-module-inner"><div class="drive-item-title"><button type="button" id="remove" class="btn btn-outline-danger btn-xs" title="Удалить файл" onclick="rmFile('+result.fileid+')"><i class="fa fa-remove" aria-hidden="true" style="color:red;"></i></button><a target="_blank" href="index.php?r=tender%2Fdownload-file&id='+result.fileid+'">'+result.fileName+'</a></div></div></div>'));

                $.toast({
                	text : 'Файл успешно загружен',
                	heading: 'Добавлен',
                	showHideTransition: 'slide',
                	loader: false,
                	loaderBg: '#9EC600',
                	position: 'top-right',
                	bgColor: '#1BA261',
                	hideAfter : 3000,
                });    
            },

            error: function(err) {
            	$.toast({
                text : 'Не удалось загрузить файл',
                heading: 'Ошибка',
                showHideTransition: 'slide',
                loader: false,
                loaderBg: '#9EC600',
                position: 'top-right',
                bgColor: '#DD5145',
                hideAfter : 7000,
            });
            }
        });
	}

	function rmFile(id)
	{
		$(".file_"+id).remove();
        $.ajax({
        	url: 'index.php?r=tender-ajax%2Fremove-file&id=' + id,
        	type: 'POST',
        	success: function(data){
        		console.log(data);
        	}
    	});
        $(this).closest('tr').remove();
        $.toast({
        	text : 'Файл успешно удален.',
        	heading: 'Удален',
        	showHideTransition: 'slide',
        	loader: false,
        	loaderBg: '#9EC600',
        	position: 'top-right',
        	bgColor: '#1BA261',
        	hideAfter : 3000,
        });  

	}	
</script>

<?php if (Yii::$app->session->hasFlash('error')): ?>
    <script>
        function modal(){
            $.toast({
                text : '<?= Yii::$app->session->getFlash('error') ?>',
                heading: 'Ошибка',
                showHideTransition: 'slide',
                loader: false,
                loaderBg: '#9EC600',
                position: 'top-right',
                bgColor: '#DD5145',
                hideAfter : 7000,
            });
        }
    </script>
<?php endif; ?>