controllers/LotController.php
<?php 

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\components\filters\AuthFilter;
use app\components\filters\LotAccessFilter;
use app\components\filters\CreateDealFilter;
use app\components\filters\TenderAccessFilter;
use app\components\filters\RiskIsActive;
use app\components\filters\SpecialistFilter;


use app\models\Lot;
use app\models\LotStatus;
use app\models\LotIndication;
use app\models\LotPercent;
use app\models\LotConclusion;
use app\models\User;
use app\models\LotSign;
use app\models\LotFile;
use app\models\DepList;
use app\models\Document;
use app\models\LotRisk;
use app\models\AppProvision;
use app\models\AgreementProvision;
use app\models\LotProtocol;
use app\models\ManagerHistory;
use app\models\ParticipateHistory;
use app\models\RiskFile;
use app\models\LotChat;



/**
 * 
 */
class LotController extends Controller
{

	public function behaviors()
	{
		return [
			[
				'class' => AuthFilter::className(),
			],
			[
				'class' => LotAccessFilter::className(),
				'only' => ['view']
 			],
			[
				'class' => TenderAccessFilter::className(),
				'only' => ['edit', 'create']
			],
			[
				'class' => CreateDealFilter::className(),
				'only' => ['create-deal', 'create-new-deal']
			],
			[
				'class' => SpecialistFilter::className(),
				'only' => ['create', 'store', 'update']
			],
		];
	}

	public function actionView($id)
	{	
		$userlist = Yii::$app->CacheComponent->getUsers();
		$deplist = Yii::$app->CacheComponent->getDepList();
		$protocols = Yii::$app->CacheComponent->getProtocols();

		$lot_info = Lot::infoByLotId($id);

		//return json_encode($lot_info);

		$lot_info['depids'] = explode(',', $lot_info['depids']);

		$managers = User::getByDepid();
		
		$documents = Document::all();
		$need_docs = Document::getById($id);

		$lot_risk = LotRisk::get($id);
		$signed_users = LotSign::all($id);
		$riskFiles = RiskFile::get($id);

		$risks = Yii::$app->RiskComponent->get($lot_risk, $signed_users, $riskFiles);

		$application_provision = AppProvision::getById($id);
		$agreement_provision = AgreementProvision::getById($id);
		
		$isNeedMakeSolution = ParticipateHistory::isNeedMakeSolution($id);
		$allSolutions = ParticipateHistory::getAllSolutions($id);
		$isNeedApproveSolution = ParticipateHistory::isNeedApproveSolution($id);
		
		$is_has_tv = Lot::isHasTv($id);
		$doc_files = Document::getDocFiles($id);
		$lot_participants = Lot::getParticipants($id);
		
		$lot_protocols = LotProtocol::getLotProtocols($id);
		$lot_protocol_files = LotProtocol::getFiles($id);
		$lot_deals = Lot::getDeals($id);
		$manager_history = ManagerHistory::get($id);

		$reasonsList = [ '0' => 'N/A', '1' => 'По квалификационной части', '2' => 'По технической части', '3' => 'По ценовой', '4' => 'Другое'];

		return $this->render('/lot/info', compact('managers', 'lot_deals', 'lot_info', 'userlist', 
			'is_has_tv', 'deplist', 'documents', 'need_docs', 'doc_files', 'lot_participants', 
			'application_provision', 'agreement_provision', 'protocols', 
			'lot_protocols', 'lot_protocol_files', 'manager_history', 'isNeedApproveSolution',
			'allSolutions', 'isNeedMakeSolution', 'risks', 'reasonsList'));
	}

	public function actionMessages($lotId)
	{	
		$lot_messages = LotChat::getLotMessages($lotId);

		return $this->asJson(['messages' => $lot_messages]);
	}

	public function actionEdit($id, $tenderid)
	{
		$lot_info = Lot::infoByLotId($id);
		$lot_statuses = Yii::$app->CacheComponent->getLotStatuses();
		$lot_indications = Yii::$app->CacheComponent->getLotIndications();
		$percents = Yii::$app->CacheComponent->getLotPercents();
		$conclusions = Yii::$app->CacheComponent->getLotConclusions();

		return $this->render('/lot/edit', compact('lot_info', 'lot_statuses', 'lot_indications', 'percents', 'conclusions'));
	}

	function get_type($elem)
	{
		return $elem['userid'];
	}

	public function actionNotify()
	{
		$lots = Lot::getLotsForNotifications();
		$final = [];
		$managers = [];

		//return json_encode($lots);

		foreach($lots as $index => $lot) {
			if(($lot['ap_is_need'] == 1 && $lot['ap_is_exist'] == 0) || ($lot['lap_is_need'] == 1 && $lot['lap_is_exist'] == 0)) {
				$final[] = $lot;
				//$managers[] = $lot['m_managerid'];
			}
		}

		if(count($final)) {

			$departments = []; 

			foreach($final as $k => $lot) {
				$query = (new \yii\db\Query())
				->select('u.userid, u.login, u.fullname, u.position, u.depid, u.email')
				->from('contracts.users u')
				->where(['blocked'=> 0])
				->andWhere(['!=', 'userid', 0])
				->andWhere(['=', 'userid', $lot['m_managerid']])
				->orderBy(['u.fullname' => SORT_ASC])
				->one();
	
				$final[$k]['depId'] = $query['depid'];
				$departments[] = (int) trim($query['depid']);
				$managers[] = [
					'userid' => $lot['m_managerid'],
					'depid' => $query['depid']
				];
			}
	
			$managers = array_unique($managers, SORT_REGULAR);
			$departments = array_unique($departments);
	
			// Form user list
	
			$users = (new \yii\db\Query())
			->select(['privusers.userid', 'privusers.depid'])
			->from('privusers')
			->where(['privusers.depid' => $departments])
			->andWhere(['privusers.tender' => [3] ])
			->all();

			// Арман Маралов 240
			// Эркин Орозакунов 1460

			$users = array_merge($users, $managers);

			//->andWhere(['=', 'privusers.tender', 1])
			//->all();
	
			/* if(count($departments)) {
	
				$users = $users->where(['privusers.depid' => $departments])->all();
				$users = array_merge($users, $managers);
	
			} else {
	
				$users = $users->all();
				$users = array_merge($users, $managers);
			} */
	
			//return json_encode($users);
			//return json_encode($final);

			foreach($final as $key => $lot) {
				foreach($users as $j => $user) {
					if($user['depid'] == $lot['depId']) {
						//return json_encode(['userid' => $user['userid'], 'lotid' => $lot['lotid']]);
						Yii::$app->MailComponent->sendToUser($user['userid'], $lot['lotid']);
					}
				}
			}

			Yii::$app->MailComponent->sendToUser(1810, $lot['lotid']);
	
			//return json_encode(['lots' => $final, 'users' => $users]);
			return json_encode(['success' => true]);
		}
	}

	public function actionUpdate($id, $tenderid)
	{
		$lot = new Lot();

		//return $lot->edit($id);

		if ($lot->edit($id)) {
			Yii::$app->session->setFlash('success', "Лот изменен успешно.");
		} else {
			Yii::$app->session->setFlash('error', "Лот не изменен.");
		}

		return $this->redirect(['lot/view', 'id'=>$id]);
	}

	public function actionCreate($tenderid)
	{
		$lot_statuses = Yii::$app->CacheComponent->getLotStatuses();
		$lot_indications = Yii::$app->CacheComponent->getLotIndications();
		$percents = Yii::$app->CacheComponent->getLotPercents();
		$conclusions = Yii::$app->CacheComponent->getLotConclusions();

		return $this->render('/lot/create', compact('lot_info', 'lot_statuses', 'lot_indications', 'percents', 'conclusions'));
	}

	public function actionStore($tenderid)
	{
		$lot = new Lot();
		$lot_file = new LotFile();
		
		if ($lot->store()) {

			$lot_file->uploadFile($lot->lotid);
			Yii::$app->session->setFlash('success', "Лот успешно создан.");
		} else {
			Yii::$app->session->setFlash('error', "Не удалось создать лот");
		}

		return $this->redirect(['lot/view', 'id'=> $lot->lotid]);
			
	}

	public function actionCreateDeal($id, $dealid)
	{
		$lot = new Lot();

		if ($lot->assignLotToDeal($id, $dealid)) {

				$this->getLinkToDeal($lot->csid, $id);
					
				Yii::$app->session->setFlash('success', "Лот был привязан к сделки из kCRM");
		} else {
			Yii::$app->session->setFlash('error', "Упс :(. Ошибка!");
		}

		return $this->redirect(['lot/view', 'id'=>$id]);
	}

	
	public function actionCreateNewDeal($id)
	{
		error_reporting(E_ALL & ~E_DEPRECATED & ~E_NOTICE);
		$lot = new Lot();

		if ($lot->createDeal($id)) {

			$this->getLinkToDeal($lot->csid, $id);
		
				Yii::$app->session->setFlash('success', "Сделка была успешно создана в kCRM");
		} else {
				Yii::$app->session->setFlash('error', "Сделка не была создана в KCRM");
		}
		
		return $this->redirect(['lot/view', 'id'=>$id]);
	}

	public function getLinkToDeal($csid, $lotid)
	{
		$soap='xreq=
            <soapenv:Envelope">
            <soapenv:Header>
            <heads:credentials">
            <heads:key>69av92us40jn</heads:key>
            </heads:credentials>
            </soapenv:Header>
            <soapenv:Body>
            <get_ecsid_by_csid>'.$csid.'</get_ecsid_by_csid>
            </soapenv:Body>
            </soapenv:Envelope>';

       	$headers = array(
            'POST /apihub/index.php',
            'Host: kcrm.kaztranscom.kz',
            'Content-Length: '.strlen($soap));

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, 'https://kcrm.kaztranscom.kz/apihub/index.php');
        curl_setopt($ch, CURLOPT_HEADER, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_USERAGENT, "Opera/9.63 (Windows NT 5.1; U; ru) Presto/2.1.1");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers); 
        curl_setopt($ch, CURLOPT_POST, true );
        curl_setopt($ch, CURLOPT_POSTFIELDS, $soap);
        $result = curl_exec($ch);
        curl_close($ch);
      
        $ecsid = $result;
       
      	if (Lot::linkToDeal($ecsid, $lotid)) {
      		Yii::$app->session->setFlash('success', "Вы успешно создали сделку в KCRM. Ссылку была сгенерирована и будет доступна в информации о лоте.");
      		return true;
		}

		return false;     	
	}

	public function actionSign($risk_id, $lotid)
	{
		if (LotSign::sign($risk_id, $lotid)) {
			Yii::$app->session->setFlash('success', "Вы успешно подписали лот, поздравляем.");
		} else {
			Yii::$app->session->setFlash('error', "К сожалению, не удалось подписать лот. Попробуйте снова.");
		}

		return $this->redirect(['lot/view', 'id'=>$lotid]);
	}

	public function actionDownloadFile($id)
	{
		return LotFile::download($id);
	}

views/lot/edit.php
<?php
use yii\helpers\Url;
use kartik\date\DatePicker;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
?>

<div class="row">
	<div class="col-md-6">
		<form action="<?= Url::toRoute(['lot/update', 'id'=> $lot_info['lotid'], 'tenderid' => $lot_info['l_tenderid']])?>" method="POST" onkeypress="return event.keyCode!=13">
			<input type="hidden" name="<?= Yii::$app->request->csrfParam; ?>" value="<?= Yii::$app->request->csrfToken; ?>" />
			<input type="hidden" name="lotid" value="<?= Yii::$app->request->get('id'); ?>">
			<table class="table" style="width:100%;background:#ffffff;border:10px solid #ffffff;">
				<tbody>
					<tr>
						<td colspan="2" class="haction1">Информация о Лоте<br><br>
						</td>
					</tr>
					<tr>
						<td class="td01">ID Лота</td>
						<td width="50%" class="td02">
							<?= $lot_info['lotid'] ?>
						</td>
					</tr>
					<tr>
						<td class="td01">Участие аффилированных лиц</td>
						<td width="50%" class="td02">
							<?=
							Select2::widget([
								'name' => 'is_affiliated',
								'hideSearch' => true,
								'value' => $lot_info['is_affiliated'],
								'data' => ['0'=>'Нет', '1'=>'Да'],
								'options' => ['multiple'=>false, 'class' => 'inp01']
							]); 
							?>
						</td>
					</tr>
					<tr>
						<td class="td01">№ (номер) Лота</td><td class="td02">
							<input name="lot_number" type="text" id="ELE_CSBIN" value="<?= $lot_info['lot_number']?>" class="inp01" autocomplete="off">
						</td>
					</tr>
					<tr>
						<td width="50%" class="td01">№ (номер), наименование Лота (ов) закупки</td><td width="50%" class="td02">
							<textarea name="lot_name" type="text" id="ELE_CSBIN" value="" class="inp01" autocomplete="off"><?= $lot_info['lot_name']?></textarea> 
						</td>
					</tr>
					<tr>
						<td class="td01">Место поставки товара / выполнения работ / оказания услуг</td><td class="td02">
							<input name="place" type="text" id="ELE_CSBIN" value="<?= $lot_info['place']?>" class="inp01" autocomplete="off">
						</td>
					</tr>
					<tr>
						<td class="td01">Дата проведения закупки (вскрытия)</td><td class="td02">
							<?=
							DatePicker::widget([
								'name' => 'date_purchase',
								'type' => DatePicker::TYPE_INPUT,
								'value' => date('d-m-Y', $lot_info['date_purchase']),
								'pluginOptions' => [
									'autoclose'=>true,
									'format' => 'dd-mm-yyyy',
								],
								'options' => ['class' => 'inp01']
							]);
							?>
						</td>
					</tr>
					<tr>
						<td class="td01">Бюджет закупки, в тенге, без учета НДС</td><td class="td02">
							<input name="budget" type="number" id="budget" value="<?= $lot_info['budget']?>" class="inp01" autocomplete="off" onkeyup = "countVat();" step="any">
						</td>
					</tr>
					<tr>
						<td class="td01">Бюджет закупки, в тенге, с учетом НДС</td><td class="td02">
							<input name="budget_vat" type="number" id="budget_vat" value="<?= $lot_info['budget_vat']?>" class="inp01" autocomplete="off" step="any">
						</td>
					</tr>
					<tr>
						<td class="td01">Статус объявленной закупки</td><td class="td02">
							<?=
							Select2::widget([
								'hideSearch' => true,
								'name' => 'lot_status',
								'value' => $lot_info['lot_status'],
								'data' => ArrayHelper::map($lot_statuses, 'lid', 'status_title'),
								'options' => ['multiple'=>false, 'class' => 'inp01']
							]); 
							?>
						</td>
					</tr>
					<tr>
						<td class="td01">Признак закупки ("Существующий" / "Новый" объем услуг АО KazTransCom)</td><td class="td02">
							<?=
							Select2::widget([
								'hideSearch' => true,
								'name' => 'purchase_indication',
								'value' => $lot_info['purchase_indication'],
								'data' => ArrayHelper::map($lot_indications, 'indicationid', 'indication_title'),
								'options' => ['multiple'=>false, 'class' => 'inp01']
							]); 
							?>
						</td>
					</tr>
					<tr>
						<td class="td01">Процент обеспечения заявки</td><td class="td02">
							<?=
							Select2::widget([
								'hideSearch' => true,
								'name' => 'percentid',
								'value' => $lot_info['percentid'],
								'data' => ArrayHelper::map($percents, 'perid', 'percent_title'),
								'options' => ['multiple'=>false, 'class' => 'inp01']
							]); 
							?>
						</td>
					</tr>
					<tr>
						<td class="td01">Ценовое предложение АО KazTransCom, в тенге, без учета НДС</td><td class="td02">
							<input name="ktc_price" type="text" id="ktc_price" value="<?= $lot_info['ktc_price']?>" class="inp01" autocomplete="off" onkeyup = "countKtcVat();" step="any">
						</td>
					</tr>
					<tr>
						<td class="td01">Ценовое предложение АО KazTransCom, в тенге, с учетом НДС</td><td class="td02">
							<input name="ktc_price_vat" type="text" id="ktc_price_vat" value="<?= $lot_info['ktc_price_vat']?>" class="inp01" autocomplete="off">
						</td>
					</tr>
					<tr>
						<td class="td01">Итоги закупки</td><td class="td02">
							<?=
							Select2::widget([
								'hideSearch' => true,
								'name' => 'lot_conclusion',
								'value' => $lot_info['lot_conclusion'],
								'data' => ArrayHelper::map($conclusions, 'concid', 'conclusion_title'),
								'options' => ['multiple'=>false, 'class' => 'inp01'],
								'pluginEvents' => [
									"select2:select" => "function(e) { 
										console.log('Selected:', e.params.data.id);
									}",
								 ]
							]); 
							?>
						</td>
					</tr>
					<tr>
						<td class="td01">Описание итогов</td><td class="td02">
							<input name="conclusion_reason" type="text" id="conclusion_reason" value="<?= $lot_info['conclusion_reason']?>" class="inp01" autocomplete="off">
						</td>
					</tr>
					<tr>
						<td class="td01">Перечень потенциальных поставщиков / участников закупки</td><td class="td02">
							<textarea name="potential_members" type="text" id="ELE_CSBIN" value="" class="inp01" autocomplete="off"><?= $lot_info['potential_members']?></textarea>	
						</td>
					</tr>
					<tr>
						<td class="td01">Тип причины отказа</td><td class="td02">
							<?=
							Select2::widget([
								'hideSearch' => true,
								'name' => 'ktc_cancel_reason',
								'value' => $lot_info['ktc_cancel_reason'],
								'data' => [ '0' => 'N/A', '1' => 'По квалификационной части', '2' => 'По технической части', '3' => 'По ценовой'],
								'options' => ['multiple'=>false, 'class' => 'inp01']
							]); 
							?>
						</td>
					</tr>
					<tr>
						<td class="td01">Детальная причина отказа</td>
						<td class="td02">
							<textarea rows="6" name="ktc_reason_cancel" type="text" id="ELE_CSBIN" value="" class="inp01" autocomplete="off"><?= $lot_info['ktc_reason_cancel']?></textarea>
						</td>
					</tr>
					<tr>
						<td class="td01">Тип причины отклонения</td><td class="td02">
							<?=
							Select2::widget([
								'hideSearch' => true,
								'name' => 'ktc_qf_reason',
								'value' => $lot_info['ktc_qf_reason'],
								'data' => [ '0' => 'N/A', '1' => 'По квалификационной части', '2' => 'По технической части', '3' => 'По ценовой'],
								'options' => ['multiple'=>false, 'class' => 'inp01']
							]); 
							?>
						</td>
					</tr>
					<tr>
						<td class="td01">Детальная причина отклонения</td>
						<td class="td02">
							<textarea rows="6" name="ktc_reason" type="text" id="ELE_CSBIN" value="" class="inp01" autocomplete="off"><?= $lot_info['ktc_reason']?></textarea>
						</td>
					</tr>
					<tr>
						<td class="td01">Ценовое предложение победителя закупок, в тенге, без учета НДС</td><td class="td02">
							<input name="winner_price" type="text" id="winner_price" value="<?= $lot_info['winner_price']?>" class="inp01" autocomplete="off" onkeyup="countWinVat();" step="any">
						</td>
					</tr>
					<tr>
						<td class="td01">Ценовое предложение победителя закупок, в тенге, с учетом НДС</td><td class="td02">
							<input name="winner_price_vat" type="text" id="winner_price_vat" value="<?= $lot_info['winner_price_vat']?>" class="inp01" autocomplete="off">
						</td>
					</tr>
					<tr>
						<td class="td01">Ссылка</td><td class="td02">
							<input name="link" type="text" id="ELE_CSBIN" value="<?= $lot_info['link']?>" class="inp01" autocomplete="off">
						</td>
					</tr>
					<tr>
						<td class="td01">Примечания</td><td class="td02">
							<textarea name="notes" type="text" id="ELE_CSBIN" value="" class="inp01" autocomplete="off"><?= $lot_info['notes']?></textarea>
						</td>
					</tr>
					<tr>
						<td class="td01">Партнер</td><td class="td02">
							<?=
							Select2::widget([
								'hideSearch' => true,
								'name' => 'partner',
								'value' => $lot_info['partner'],
								'data' => ['0'=>'Нет', '1'=>'Да'],
								'options' => ['multiple'=>false, 'class' => 'inp01']
							]); 
							?>
						</td>
					</tr>
					<tr>
						<td class="td01">Номер договора в случае выигрыша закупа</td><td class="td02">
							<input name="dogovor_number" type="text" id="ELE_CSBIN" value="<?= $lot_info['dogovor_number']?>" class="inp01" autocomplete="off">
						</td>
					</tr>
					<tr>
						<td class="td01">Дата договора в случае выигрыша закупки</td><td class="td02">
							<?=
							DatePicker::widget([
								'name' => 'dogovor_date',
								'type' => DatePicker::TYPE_INPUT,
								'value' => date('d-m-Y', $lot_info['dogovor_date']),
								'pluginOptions' => [
									'autoclose'=>true,
									'format' => 'dd-mm-yyyy',
								],
								'options' => ['class' => 'inp01']
							]);
							?>
						</td>
					</tr>
					<tr>
						<td class="td01">Файлы</td>
						<td class="td02" id="lot_files">
							<input name="tender_file" type="file" value="" id="lot_file" class="inp01" accept=".xlsx,.xls,image/*,.doc, .docx,.ppt, .pptx,.txt,.pdf" onchange="updateFile(<?= Yii::$app->request->get('id')?>);">

							<?php foreach ($lot_info['files'] as $key => $value): ?>
								<div class="<?= 'file_'.$value['fileid']?>">
									<div class="drive-item module">
										<div class="drive-item-inner module-inner">
											<div class="drive-item-title"><button type="button" id="remove" class="btn btn-outline-danger btn-xs" title="Удалить файл" onclick="rmFile(<?=$value['fileid']?>)"><i class="fa fa-remove" aria-hidden="true" style="color:red;"></i></button><a target="_blank" href="<?= Url::toRoute(['lot/download-file', 'id'=>$value['fileid']])?>"><?= pathinfo($value['f_path'])['filename'].'.'.pathinfo($value['f_path'])['extension'] ?></a></div>
										</div>
									</div>
								</div>
							<?php endforeach ?>
						</td>
					</tr>
				</tbody>
			</table>
			<button class="btn btn-default" type="submit">Сохранить</button>
		</form>
	</div>
	<div class="col-md-6">
		
	</div>
</div>
<script src="<?= Yii::$app->params['module_folder_name'] ?>js/lotEdit.js"></script>